# NER zero shot transfer to
# Selected wikiann languages
# MasakhaNER

_target_: trident.TridentDataModule
_recursive_: false

datamodule_cfg:
  remove_unused_columns: true
  keep_raw_dataset: false
  setup:
    _target_: trident.utils.data.setup
    _recursive_: false
  on_after_setup:
    _target_: src.tasks.token_classification.processor.on_after_setup
    max_length: 510
    tokenizer:
      _target_: transformers.AutoTokenizer.from_pretrained
      pretrained_model_name_or_path: ${module.model.pretrained_model_name_or_path}
    column_names:
      text: tokens
      label: pos_tags

dataloader_cfg:
  _target_: torch.utils.data.dataloader.DataLoader
  collate_fn:
    _target_: transformers.data.data_collator.DataCollatorForTokenClassification
    tokenizer:
      _target_: transformers.AutoTokenizer.from_pretrained
      pretrained_model_name_or_path: ${module.model.pretrained_model_name_or_path}
    max_length: 510
    padding: true
  train:
    batch_size: 32
    shuffle: true
  val:
    batch_size: 256
    shuffle: false
  test:
    batch_size: 256
    shuffle: false

dataset_cfg:
  _target_: datasets.load.load_dataset
  train:
    path: xtreme
    name: udpos.English
    split: train
  val:
    _datasets_:
      validation_udpos_Afrikaans:
        path: xtreme
        name: udpos.Afrikaans
        split: validation
      validation_udpos_Arabic:
        path: xtreme
        name: udpos.Arabic
        split: validation
      validation_udpos_Basque:
        path: xtreme
        name: udpos.Basque
        split: validation
      validation_udpos_Bulgarian:
        path: xtreme
        name: udpos.Bulgarian
        split: validation
      validation_udpos_Dutch:
        path: xtreme
        name: udpos.Dutch
        split: validation
      validation_udpos_English:
        path: xtreme
        name: udpos.English
        split: validation
      validation_udpos_Estonian:
        path: xtreme
        name: udpos.Estonian
        split: validation
      validation_udpos_Finnish:
        path: xtreme
        name: udpos.Finnish
        split: validation
      validation_udpos_French:
        path: xtreme
        name: udpos.French
        split: validation
      validation_udpos_German:
        path: xtreme
        name: udpos.German
        split: validation
      validation_udpos_Greek:
        path: xtreme
        name: udpos.Greek
        split: validation
      validation_udpos_Hebrew:
        path: xtreme
        name: udpos.Hebrew
        split: validation
      validation_udpos_Hindi:
        path: xtreme
        name: udpos.Hindi
        split: validation
      validation_udpos_Hungarian:
        path: xtreme
        name: udpos.Hungarian
        split: validation
      validation_udpos_Indonesian:
        path: xtreme
        name: udpos.Indonesian
        split: validation
      validation_udpos_Italian:
        path: xtreme
        name: udpos.Italian
        split: validation
      validation_udpos_Japanese:
        path: xtreme
        name: udpos.Japanese
        split: validation
      validation_udpos_Korean:
        path: xtreme
        name: udpos.Korean
        split: validation
      validation_udpos_Chinese:
        path: xtreme
        name: udpos.Chinese
        split: validation
      validation_udpos_Marathi:
        path: xtreme
        name: udpos.Marathi
        split: validation
      validation_udpos_Persian:
        path: xtreme
        name: udpos.Persian
        split: validation
      validation_udpos_Portuguese:
        path: xtreme
        name: udpos.Portuguese
        split: validation
      validation_udpos_Russian:
        path: xtreme
        name: udpos.Russian
        split: validation
      validation_udpos_Spanish:
        path: xtreme
        name: udpos.Spanish
        split: validation
      validation_udpos_Tamil:
        path: xtreme
        name: udpos.Tamil
        split: validation
      validation_udpos_Telugu:
        path: xtreme
        name: udpos.Telugu
        split: validation
      validation_udpos_Turkish:
        path: xtreme
        name: udpos.Turkish
        split: validation
      validation_udpos_Urdu:
        path: xtreme
        name: udpos.Urdu
        split: validation
      validation_udpos_Vietnamese:
        path: xtreme
        name: udpos.Vietnamese
        split: validation
      test_udpos_Afrikaans:
        path: xtreme
        name: udpos.Afrikaans
        split: test
      test_udpos_Arabic:
        path: xtreme
        name: udpos.Arabic
        split: test
      test_udpos_Basque:
        path: xtreme
        name: udpos.Basque
        split: test
      test_udpos_Bulgarian:
        path: xtreme
        name: udpos.Bulgarian
        split: test
      test_udpos_Dutch:
        path: xtreme
        name: udpos.Dutch
        split: test
      test_udpos_English:
        path: xtreme
        name: udpos.English
        split: test
      test_udpos_Estonian:
        path: xtreme
        name: udpos.Estonian
        split: test
      test_udpos_Finnish:
        path: xtreme
        name: udpos.Finnish
        split: test
      test_udpos_French:
        path: xtreme
        name: udpos.French
        split: test
      test_udpos_German:
        path: xtreme
        name: udpos.German
        split: test
      test_udpos_Greek:
        path: xtreme
        name: udpos.Greek
        split: test
      test_udpos_Hebrew:
        path: xtreme
        name: udpos.Hebrew
        split: test
      test_udpos_Hindi:
        path: xtreme
        name: udpos.Hindi
        split: test
      test_udpos_Hungarian:
        path: xtreme
        name: udpos.Hungarian
        split: test
      test_udpos_Indonesian:
        path: xtreme
        name: udpos.Indonesian
        split: test
      test_udpos_Italian:
        path: xtreme
        name: udpos.Italian
        split: test
      test_udpos_Japanese:
        path: xtreme
        name: udpos.Japanese
        split: test
      test_udpos_Kazakh:
        path: xtreme
        name: udpos.Kazakh
        split: test
      test_udpos_Korean:
        path: xtreme
        name: udpos.Korean
        split: test
      test_udpos_Chinese:
        path: xtreme
        name: udpos.Chinese
        split: test
      test_udpos_Marathi:
        path: xtreme
        name: udpos.Marathi
        split: test
      test_udpos_Persian:
        path: xtreme
        name: udpos.Persian
        split: test
      test_udpos_Portuguese:
        path: xtreme
        name: udpos.Portuguese
        split: test
      test_udpos_Russian:
        path: xtreme
        name: udpos.Russian
        split: test
      test_udpos_Spanish:
        path: xtreme
        name: udpos.Spanish
        split: test
      test_udpos_Tagalog:
        path: xtreme
        name: udpos.Tagalog
        split: test
      test_udpos_Tamil:
        path: xtreme
        name: udpos.Tamil
        split: test
      test_udpos_Telugu:
        path: xtreme
        name: udpos.Telugu
        split: test
      test_udpos_Thai:
        path: xtreme
        name: udpos.Thai
        split: test
      test_udpos_Turkish:
        path: xtreme
        name: udpos.Turkish
        split: test
      test_udpos_Urdu:
        path: xtreme
        name: udpos.Urdu
        split: test
      test_udpos_Vietnamese:
        path: xtreme
        name: udpos.Vietnamese
        split: test
      test_udpos_Yoruba:
        path: xtreme
        name: udpos.Yoruba
        split: test
  test: 
    _datasets_:
      test_udpos_Afrikaans:
        path: xtreme
        name: udpos.Afrikaans
        split: test
      test_udpos_Arabic:
        path: xtreme
        name: udpos.Arabic
        split: test
      test_udpos_Basque:
        path: xtreme
        name: udpos.Basque
        split: test
      test_udpos_Bulgarian:
        path: xtreme
        name: udpos.Bulgarian
        split: test
      test_udpos_Dutch:
        path: xtreme
        name: udpos.Dutch
        split: test
      test_udpos_English:
        path: xtreme
        name: udpos.English
        split: test
      test_udpos_Estonian:
        path: xtreme
        name: udpos.Estonian
        split: test
      test_udpos_Finnish:
        path: xtreme
        name: udpos.Finnish
        split: test
      test_udpos_French:
        path: xtreme
        name: udpos.French
        split: test
      test_udpos_German:
        path: xtreme
        name: udpos.German
        split: test
      test_udpos_Greek:
        path: xtreme
        name: udpos.Greek
        split: test
      test_udpos_Hebrew:
        path: xtreme
        name: udpos.Hebrew
        split: test
      test_udpos_Hindi:
        path: xtreme
        name: udpos.Hindi
        split: test
      test_udpos_Hungarian:
        path: xtreme
        name: udpos.Hungarian
        split: test
      test_udpos_Indonesian:
        path: xtreme
        name: udpos.Indonesian
        split: test
      test_udpos_Italian:
        path: xtreme
        name: udpos.Italian
        split: test
      test_udpos_Japanese:
        path: xtreme
        name: udpos.Japanese
        split: test
      test_udpos_Kazakh:
        path: xtreme
        name: udpos.Kazakh
        split: test
      test_udpos_Korean:
        path: xtreme
        name: udpos.Korean
        split: test
      test_udpos_Chinese:
        path: xtreme
        name: udpos.Chinese
        split: test
      test_udpos_Marathi:
        path: xtreme
        name: udpos.Marathi
        split: test
      test_udpos_Persian:
        path: xtreme
        name: udpos.Persian
        split: test
      test_udpos_Portuguese:
        path: xtreme
        name: udpos.Portuguese
        split: test
      test_udpos_Russian:
        path: xtreme
        name: udpos.Russian
        split: test
      test_udpos_Spanish:
        path: xtreme
        name: udpos.Spanish
        split: test
      test_udpos_Tagalog:
        path: xtreme
        name: udpos.Tagalog
        split: test
      test_udpos_Tamil:
        path: xtreme
        name: udpos.Tamil
        split: test
      test_udpos_Telugu:
        path: xtreme
        name: udpos.Telugu
        split: test
      test_udpos_Thai:
        path: xtreme
        name: udpos.Thai
        split: test
      test_udpos_Turkish:
        path: xtreme
        name: udpos.Turkish
        split: test
      test_udpos_Urdu:
        path: xtreme
        name: udpos.Urdu
        split: test
      test_udpos_Vietnamese:
        path: xtreme
        name: udpos.Vietnamese
        split: test
      test_udpos_Yoruba:
        path: xtreme
        name: udpos.Yoruba
        split: test
